"""HTMLExporter - Exports reports to HTML format."""

from typing import Any, Dict
from pathlib import Path
from datetime import datetime
from .base_worker import BaseWorker, WorkerResult, ErrorType


class HTMLExporter(BaseWorker):
    """Exports reports to HTML format."""
    
    def __init__(self):
        super().__init__("html_exporter")
    
    def execute(self, report_data: Dict[str, Any], file_path: str = None, **kwargs) -> WorkerResult:
        """Export report to HTML.
        
        Args:
            report_data: Report dictionary to export
            file_path: Output file path
            **kwargs: Additional parameters
            
        Returns:
            WorkerResult with export information
        """
        result = self._create_result(
            success=True,
            task_type="html_export",
            data={}
        )
        
        try:
            if report_data is None or not isinstance(report_data, dict):
                self._add_error(
                    result,
                    ErrorType.DATA_VALIDATION_ERROR,
                    "Report data must be a dictionary",
                    severity="error"
                )
                return result
            
            if file_path is None:
                timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
                file_path = f"report_{timestamp}.html"
            
            self.logger.info(f"Exporting to HTML: {file_path}")
            
            html_content = self._generate_html(report_data)
            
            with open(file_path, 'w') as f:
                f.write(html_content)
            
            file_size = Path(file_path).stat().st_size
            
            result.data = {
                "status": "success",
                "format": "HTML",
                "file_path": str(file_path),
                "file_size": file_size,
                "message": f"Report exported successfully to {file_path}",
            }
            
        except Exception as e:
            self._add_error(
                result,
                ErrorType.COMPUTATION_ERROR,
                f"Export failed: {str(e)}",
                severity="error"
            )
            result.success = False
        
        return result
    
    def _generate_html(self, report: Dict[str, Any]) -> str:
        """Generate HTML content from report.
        
        Args:
            report: Report dictionary
            
        Returns:
            HTML content string
        """
        title = "Data Analysis Report"
        timestamp = datetime.utcnow().isoformat()
        
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            border-radius: 8px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 2.5em;
        }}
        .section {{
            background: white;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        .metric {{
            display: inline-block;
            background: #f0f4ff;
            padding: 15px 20px;
            margin: 10px 10px 10px 0;
            border-radius: 6px;
            border-left: 4px solid #667eea;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }}
        table th {{
            background: #667eea;
            color: white;
            padding: 12px;
            text-align: left;
        }}
        table td {{
            padding: 12px;
            border-bottom: 1px solid #ddd;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <p>Generated: {timestamp}</p>
    </div>
    <div class="section">
        <h2>Report Summary</h2>
        <p>This report was generated by GOAT Data Analyst</p>
    </div>
</body>
</html>
"""
        return html
